
<div id="fastorder-component" data-bind="scope:'fastorder'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#fastorder-component": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "fastorder": {
                        "component": "AHT_Fastorder/js/fastorder-component",
                        "template": "AHT_Fastorder/fastorder-component"
                    }
                }
            }
        }
    }
    </script>
</div>